### ISSUE TITLE
Classroom-Setup Error with AWS region.

### ISSUE THREAD

**Issue by JGillette71** [databricks-academy/dbacademy#8] opened 2022-12-19 23:06 UTC
Hello, 

I am attempting to set up Apache Spark Programming with Databricks, but I'm receiving the following error. 
_ERROR: Unable to mount..._
_Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied; request:..._

I've traced this error to command 3 in the following notebook. 
databricks_academy/Apache-Spark-Programming-with-Databricks/Includes/Common-Notebooks/Utilities-Datasets

My cluster is hosted in an AWS region not listed in _AWS_REGION_MAP()_ and my S3 bucket has it's own security credetials.

Please advise on edits to accommodate additional region and security credentials. 

Thank you.

**Comment by JGillette71** [comment] 2022-12-21 18:41
Alternatively, can the datasets for each course be made available for manual upload into the student workspace? 

I've tried contacting customer support several times. Can't seem to gain any traction on this issue.

**Comment by SireInsectus** [comment] 2023-04-28 19:12
@JGillette71, I really doubt that this comment, 4-5 months later, will do you any good, but the code you are looking at isn't even used anymore and hasn't been for a long time (years?). I wrote the logic you are referring to years ago and given the function name alone, I can confirm you were using a REALLY outdated version of that courseware.

In case you get this message in time, you can download the latest and greatest from that course's GitHub releases page at https://github.com/databricks-academy/apache-spark-programming-with-databricks-english/releases.

That repo will soon be made private and archived as we are moving to a new distribution model. You should grab it as soon as you get this message.

And as to why it's taken so long to reply to this issue... this repo is only public as an implementation side effect for related projects; we don't track bugs, PRs, or anything else using these GitHub features. And because we don't use it, we don't monitor it either.

**Closed by SireInsectus** 2023-04-28 19:12 UTC
